const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description: 'Bluetooth technology lets you connect it with compatible devices wirelessly.',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description: 'Introducing the iPhone 11 Pro. A transformative triple-camera system.',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description: 'The ultimate home entertainment center starts with PlayStation.',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description: 'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse.',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  }
];

export default products;